# Generated by Django 5.2.4 on 2026-04-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='РќР°Р·РІР°РЅРёРµ')),
                ('description', models.TextField(blank=True, verbose_name='РћРїРёСЃР°РЅРёРµ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Р”Р°С‚Р° СЃРѕР·РґР°РЅРёСЏ')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='GitHub')),
                ('status', models.CharField(choices=[('open', 'РћС‚РєСЂС‹С‚'), ('closed', 'Р—Р°РєСЂС‹С‚')], default='open', max_length=6, verbose_name='РЎС‚Р°С‚СѓСЃ')),
            ],
            options={
                'verbose_name': 'РџСЂРѕРµРєС‚',
                'verbose_name_plural': 'РџСЂРѕРµРєС‚С‹',
                'ordering': ['-created_at'],
            },
        ),
    ]
