from enum import StrEnum

USER_NAME_MAX_LENGTH = 124
USER_SURNAME_MAX_LENGTH = 124
USER_PHONE_MAX_LENGTH = 12
USER_ABOUT_MAX_LENGTH = 256

PHONE_REGEX = r"^(\+7|8)?\d{10}$"
PHONE_CLEAN_PATTERN = r"[\s\-\(\)]"
PHONE_EIGHT_PREFIX = "8"
PHONE_RUSSIAN_PREFIX = "+7"

AVATAR_UPLOAD_TO = "avatars/"
AVATAR_SIZE = (200, 200)
AVATAR_FONT_SIZE = 100
AVATAR_FONT_NAME = "arial.ttf"
AVATAR_DEFAULT_LETTER = "?"
AVATAR_TEXT_ANCHOR = (0, 0)
AVATAR_TEXT_COLOR = "#FFFFFF"
AVATAR_FORMAT = "PNG"


class AvatarColor(StrEnum):
    BLUE = "#4A90E2"
    TURQUOISE = "#50E3C2"
    ORANGE = "#F5A623"
    RED = "#D0021B"
    BROWN = "#8B572A"
    LIGHT_GREEN = "#7ED321"
    DARK_GREEN = "#417505"
    PINK = "#BD10E0"
    PURPLE = "#9013FE"
    GRAY = "#4A4A4A"


AVATAR_COLORS = tuple(color.value for color in AvatarColor)
